### ISSUE TITLE
Selecting a chapter from table of contents is disconnected from navigation

### ISSUE THREAD

**Issue by hxka** [shenzhuxi/readiator#4]
For example, imagine I'm reading chapter 2. Selecting previous/next chapter would switch me to chapter 1/3. Then I select chapter 5 from table of contents. Selecting previous/next chapter would switch me to chapter 1/3 anyway, instead of 4/6.

**Comment by hxka** [comment]
Also it'll be great if the current chapter was highlighted in the toc.

**Comment by shenzhuxi** [comment]
Can you provide more information about the toc issue please? I can't reproduce it on my Chrome . 
Does it happen with all your epub files or only specific ones?

About the toc highlight, it's impossible to do that for all epub files, because the toc is just a bunch of urls which can be duplicated or contain anchors.

**Comment by hxka** [comment]
Huh, it seems it only happens in [this](http://libgen.io/book/index.php?md5=D025A800C6ED3C9CE21AAD6F15B8DB15) epub. Maybe it's malformed.
